# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('pswd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
