# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elm', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('food', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
                ('restaurant', models.CharField(max_length=50)),
                ('orderid', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=20)),
            ],
        ),
    ]
